<a href="https://colab.research.google.com/github/AnaSofia29345/Proyecto-IA/blob/main/02%20-%20preprocesado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [169]:
#se cargan los datos de la competición de Kaggle
!pip install opendatasets
import opendatasets as od
dataset_link = "https://www.kaggle.com/competitions/udea-ai4eng-20242"
od.download(dataset_link)
import os
os.chdir("udea-ai4eng-20242")
os.listdir()

Requirement already satisfied: opendatasets in /usr/local/lib/python3.10/dist-packages (0.1.22)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from opendatasets) (4.66.6)
Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (from opendatasets) (1.6.17)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from opendatasets) (8.1.7)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2024.8.30)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.2.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.10)
Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: anasofia29
Your Kaggle Key: ··········
Downloading udea-ai4eng-20242.zip to ./udea-ai4eng-20242

100%|██████████| 20.1M/20.1M [00:00<00:00, 114MB/s]

Extracting archive ./udea-ai4eng-20242/udea-ai4eng-20242.zip to ./udea-ai4eng-20242

['test.csv', 'train.csv', 'submission_example.csv']

In [170]:
#se cargan los datos de train
import pandas as pd
y = pd.read_csv('/content/udea-ai4eng-20242/train.csv')
y.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,ESTU_PAGOMATRICULAPROPIO,RENDIMIENTO_GLOBAL
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Postgrado,No,medio-alto
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Técnica o tecnológica incompleta,No,bajo
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,No,bajo
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Secundaria (Bachillerato) completa,No,alto
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Primaria completa,No,medio-bajo

In [171]:
#se muestra la forma del dataframe
print ("shape of loaded dataframe", y.shape)

shape of loaded dataframe (692500, 12)

In [172]:
#Se observa la cantidad de datos faltantes que hay en cada una de las columnas
k = y.isna().sum()
k[k!=0]

ESTU_VALORMATRICULAUNIVERSIDAD     6287
ESTU_HORASSEMANATRABAJA           30857
FAMI_ESTRATOVIVIENDA              32137
FAMI_TIENEINTERNET                26629
FAMI_EDUCACIONPADRE               23178
FAMI_EDUCACIONMADRE               23664
ESTU_PAGOMATRICULAPROPIO           6498
dtype: int64

In [173]:
#Luego, se analiza el tipo de variables que tiene cada columna, si son categóricas o númericas.
for c in y.columns:
    print ("%20s"%c, y[c].dtype)

                  ID int64
             PERIODO int64
 ESTU_PRGM_ACADEMICO object
ESTU_PRGM_DEPARTAMENTO object
ESTU_VALORMATRICULAUNIVERSIDAD object
ESTU_HORASSEMANATRABAJA object
FAMI_ESTRATOVIVIENDA object
  FAMI_TIENEINTERNET object
 FAMI_EDUCACIONPADRE object
 FAMI_EDUCACIONMADRE object
ESTU_PAGOMATRICULAPROPIO object
  RENDIMIENTO_GLOBAL object

In [174]:
"""
Luego de mostrar los datos, se va a realizar un  preprocesado de los mismos para mirar que tan influyentes pueden ser para el modelo
que se va a construir para predecir el rendimiento global de los estudiantes.En este caso, existe la posibilidad de convertir varias columnas que estan en forma categorica
a variables numericas, por ejemplo las horas a la semana que trabaja cada estudiante,el estrato de vivienda, pago matricula propia, etc.En concreto se va a realizar para las
columnas de número de horas a la semana que trabaja cada estudiante,  el estrato de vivienda, el valor de la matricula de la universidad,fami_tieneinternet,
educación padre, la columna de si el estudiante paga matricula propia .
 Vamos a realizar un one-hot encoding para la columna de el numero de horas
a la semana que trabaja cada estudiante y la educacion del padre y la madre y vamos a convertir la columna de el estrato de vivienda y valor de la
matricula de la universidad y la columna de si el estudiante paga matricula propia  en un hot-hot encoding continuo.
"""
Y=pd.read_csv('/content/udea-ai4eng-20242/train.csv')
y=Y.copy()
y= y[['ESTU_HORASSEMANATRABAJA', 'FAMI_ESTRATOVIVIENDA','ESTU_PAGOMATRICULAPROPIO','ESTU_VALORMATRICULAUNIVERSIDAD', 'FAMI_TIENEINTERNET','FAMI_EDUCACIONPADRE', 'RENDIMIENTO_GLOBAL']]

In [ ]:
#Se observa que en la columna de las horas a la semana que trabaja cada estudiante hay 30857 valores perdidos y en la columna Fami_Estrato vivienda hay 32137

In [175]:
#Luego,se sustituyen los valores perdidos faltantes de estas columnas con el simbolo no info

y.ESTU_HORASSEMANATRABAJA.values[y.ESTU_HORASSEMANATRABAJA.isna()] = 'no info'
y.FAMI_ESTRATOVIVIENDA.values[y.FAMI_ESTRATOVIVIENDA.isna()] = 'no info'
y.ESTU_PAGOMATRICULAPROPIO.values[y.ESTU_PAGOMATRICULAPROPIO.isna()] = 'no info'
y.ESTU_VALORMATRICULAUNIVERSIDAD.values[y.ESTU_VALORMATRICULAUNIVERSIDAD.isna()] = 'no info'

y.FAMI_EDUCACIONPADRE.values[y.FAMI_EDUCACIONPADRE.isna()] = 'no info'

sum(y.ESTU_HORASSEMANATRABAJA.isna()), sum(y.FAMI_ESTRATOVIVIENDA.isna()), sum(y.ESTU_PAGOMATRICULAPROPIO.isna()), sum(y.ESTU_VALORMATRICULAUNIVERSIDAD.isna()),sum(y.FAMI_EDUCACIONPADRE.isna())

(0, 0, 0, 0, 0)

In [176]:
#se convierten en variables numericas el valor de la columna del estrato de vivienda de la familia
import numpy as np
#se crea una copia del dataframe
df=y.copy()


#se le asignan valores númericos a cada uno de los estratos y a los datos faltantes de la columna del estrato de vivienda
cmap={'Estrato 6':6,
      'Estrato 5':5,
      'Estrato 4':4,
      'Estrato 3':3,
      'Estrato 2':2,
      'Estrato 1':1,
      'sin estrato':0,
      'no info':-1}
y.FAMI_ESTRATOVIVIENDA=df.FAMI_ESTRATOVIVIENDA.map(cmap)
y.FAMI_ESTRATOVIVIENDA.unique()
y.FAMI_ESTRATOVIVIENDA.value_counts()


#Se observan los estratos en los que viven cada uno de los estudiantes con sus respectivos valores númericos

FAMI_ESTRATOVIVIENDA
 2.0    232671
 3.0    210685
 1.0    111991
 4.0     65514
-1.0     32137
 5.0     23608
 6.0     12605
Name: count, dtype: int64

In [177]:
#se juntan la informacion de no sabe o no se aplica para las horas a la semana que trabaja cada estudiante
df.ESTU_HORASSEMANATRABAJA=['no info' if i in ['No sabe', 'No Aplica'] else i for i in df.ESTU_HORASSEMANATRABAJA.values]
df.ESTU_HORASSEMANATRABAJA.unique()

array(['Menos de 10 horas', '0', 'Más de 30 horas', 'Entre 21 y 30 horas',
       'Entre 11 y 20 horas', 'no info'], dtype=object)

In [178]:
#se muestran los datos de las horas a la semana que trabajan cada uno de los estudiantes y tambíen de aquellos que no se tiene información.
df.ESTU_HORASSEMANATRABAJA.value_counts()

ESTU_HORASSEMANATRABAJA
Más de 30 horas        249352
0                      116550
Entre 11 y 20 horas    115857
Entre 21 y 30 horas     92693
Menos de 10 horas       87191
no info                 30857
Name: count, dtype: int64

In [179]:
#Luego, se va a crear un one-hot encoding , primero se va a hacer un mapeo
sorted_series=sorted
sorted_series
x=y.ESTU_HORASSEMANATRABAJA.sort_values()
x
ESTU_HORASSEMANATRABAJA_vals=x.unique()
ESTU_HORASSEMANATRABAJA_vals
ESTU_HORASSEMANATRABAJA_vals_onehot_vals={val: np.eye(len(ESTU_HORASSEMANATRABAJA_vals))[i] for i,val in enumerate(ESTU_HORASSEMANATRABAJA_vals)}
ESTU_HORASSEMANATRABAJA_vals_onehot_vals

{'0': array([1., 0., 0., 0., 0., 0.]),
 'Entre 11 y 20 horas': array([0., 1., 0., 0., 0., 0.]),
 'Entre 21 y 30 horas': array([0., 0., 1., 0., 0., 0.]),
 'Menos de 10 horas': array([0., 0., 0., 1., 0., 0.]),
 'Más de 30 horas': array([0., 0., 0., 0., 1., 0.]),
 'no info': array([0., 0., 0., 0., 0., 1.])}

In [180]:
ESTU_HORASSEMANATRABAJA_onehot_enc = np.r_[[ESTU_HORASSEMANATRABAJA_vals_onehot_vals[i] for i in y.ESTU_HORASSEMANATRABAJA]]
ESTU_HORASSEMANATRABAJA_onehot_enc

array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [181]:
#Posteriormente, se aplica el one-hot encoding y todas las columnas quedan en un solo dataframe
ESTU_HORASSEMANATRABAJA_df = pd.DataFrame(ESTU_HORASSEMANATRABAJA_onehot_enc, columns=[f"ESTU_HORASSEMANATRABAJA__{v}" for v in ESTU_HORASSEMANATRABAJA_vals_onehot_vals])
ESTU_HORASSEMANATRABAJA_df

,ESTU_HORASSEMANATRABAJA__0,ESTU_HORASSEMANATRABAJA__Entre 11 y 20 horas,ESTU_HORASSEMANATRABAJA__Entre 21 y 30 horas,ESTU_HORASSEMANATRABAJA__Menos de 10 horas,ESTU_HORASSEMANATRABAJA__Más de 30 horas,ESTU_HORASSEMANATRABAJA__no info
0,0.0,0.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...
692495,0.0,1.0,0.0,0.0,0.0,0.0
692496,0.0,0.0,0.0,0.0,1.0,0.0
692497,0.0,0.0,0.0,1.0,0.0,0.0
692498,0.0,0.0,0.0,1.0,0.0,0.0
692499,0.0,0.0,0.0,0.0,1.0,0.0

In [182]:
#Luego tomamos la columna del valor de la matricula de la universidad y reemplazamos los valores de cmap
cmap = {'Entre 1 millón y menos de 2.5 millones': .175,
 'Entre 2.5 millones y menos de 4 millones': .325,
 'Menos de 500 mil': .250,
 'Entre 500 mil y menos de 1 millón': .75,
 'Entre 4 millones y menos de 5.5 millones': .475,
 'Más de 7 millones': .775,
 'Entre 5.5 millones y menos de 7 millones': .625,
 'No pagó matrícula': 0,
 'no info': -1}

y.ESTU_VALORMATRICULAUNIVERSIDAD=df.ESTU_VALORMATRICULAUNIVERSIDAD.map(cmap)
y.ESTU_VALORMATRICULAUNIVERSIDAD.unique().sort()
y.ESTU_VALORMATRICULAUNIVERSIDAD.value_counts()
#Posteriormente, la columna queda en datos nnúmericos

ESTU_VALORMATRICULAUNIVERSIDAD
 0.175    204048
 0.325    127430
 0.250     80263
 0.750     78704
 0.475     69736
 0.775     68014
 0.625     38490
 0.000     19528
-1.000      6287
Name: count, dtype: int64

In [183]:
#luego miramos los valores de no sabe y no aplica en la columna de educacion del padre
y.FAMI_EDUCACIONPADRE = ['no info' if i in ['No sabe', 'No Aplica'] else i for i in y.FAMI_EDUCACIONPADRE.values]
y.FAMI_EDUCACIONPADRE.value_counts() #se muestran los valores de como es la educación del padre

FAMI_EDUCACIONPADRE
Secundaria (Bachillerato) completa      128289
Primaria incompleta                     125675
Educación profesional completa           83117
Secundaria (Bachillerato) incompleta     71654
Técnica o tecnológica completa           62995
Primaria completa                        55958
no info                                  48999
Postgrado                                44169
Educación profesional incompleta         27084
Técnica o tecnológica incompleta         22552
Ninguno                                  22008
Name: count, dtype: int64

In [184]:
#Posteriormente, le aplicamos un one-hot encoding a esta columna
FAMI_EDUCACIONPADRE_vals=y.FAMI_EDUCACIONPADRE.sort_values().unique()
FAMI_EDUCACIONPADRE_vals_onehot_vals={val: np.eye(len(FAMI_EDUCACIONPADRE_vals))[i] for i,val in enumerate(FAMI_EDUCACIONPADRE_vals)}
FAMI_EDUCACIONPADRE_onehot_enc = np.r_[[FAMI_EDUCACIONPADRE_vals_onehot_vals[i] for i in y.FAMI_EDUCACIONPADRE]]
FAMI_EDUCACIONPADRE_df = pd.DataFrame(FAMI_EDUCACIONPADRE_onehot_enc, columns=[f"FAMI_EDUCACIONPADRE__{v}" for v in FAMI_EDUCACIONPADRE_vals_onehot_vals])
FAMI_EDUCACIONPADRE_df

,FAMI_EDUCACIONPADRE__Educación profesional completa,FAMI_EDUCACIONPADRE__Educación profesional incompleta,FAMI_EDUCACIONPADRE__Ninguno,FAMI_EDUCACIONPADRE__Postgrado,FAMI_EDUCACIONPADRE__Primaria completa,FAMI_EDUCACIONPADRE__Primaria incompleta,FAMI_EDUCACIONPADRE__Secundaria (Bachillerato) completa,FAMI_EDUCACIONPADRE__Secundaria (Bachillerato) incompleta,FAMI_EDUCACIONPADRE__Técnica o tecnológica completa,FAMI_EDUCACIONPADRE__Técnica o tecnológica incompleta,FAMI_EDUCACIONPADRE__no info
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
692495,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
692496,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
692497,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
692498,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
692499,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [185]:
#se muestran los valores de los estudiantes que pagan matricula propia y los que no y tambien de los cuales no se tiene informacion

y.ESTU_PAGOMATRICULAPROPIO.value_counts()

ESTU_PAGOMATRICULAPROPIO
No         382201
Si         303801
no info      6498
Name: count, dtype: int64

In [186]:
#se muestran los valores unicos de esta columna
np.unique(y.ESTU_PAGOMATRICULAPROPIO)

array(['No', 'Si', 'no info'], dtype=object)

In [187]:
#se va a asignar valores de 0 para los estudiantes que no pagan matricula propia y valores de 1 para los que si
y.ESTU_PAGOMATRICULAPROPIO.values[y.ESTU_PAGOMATRICULAPROPIO == "Si"] = 1
y.ESTU_PAGOMATRICULAPROPIO.values[y.ESTU_PAGOMATRICULAPROPIO == "No"] = 0

In [188]:
#aplicamos lo mismo para la columna de si la familia tiene internet
y.FAMI_TIENEINTERNET.values[y.FAMI_TIENEINTERNET.isna()] = "No"
sum(y.FAMI_TIENEINTERNET.isna())
x = y.FAMI_TIENEINTERNET.values
FAMI_TIENEINTERNET_vals = sorted(np.unique(x))
FAMI_TIENEINTERNET_onehot_vals = {val: np.eye(len(FAMI_TIENEINTERNET_vals))[i] for i,val in enumerate(FAMI_TIENEINTERNET_vals)}
FAMI_TIENEINTERNET_onehot_vals
FAMI_TIENEINTERNET_onehot_enc = np.r_[[FAMI_TIENEINTERNET_onehot_vals[i] for i in y.FAMI_TIENEINTERNET]]
FAMI_TIENEINTERNET_onehot_enc

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [189]:
#se muestra la columna anterior con el one-hot
FAMI_TIENEINTERNET_df = pd.DataFrame(FAMI_TIENEINTERNET_onehot_enc, columns=[f"FAMI_TIENEINTERNET__{v}" for v in FAMI_TIENEINTERNET_onehot_vals])
FAMI_TIENEINTERNET_df

        FAMI_TIENEINTERNET__No  FAMI_TIENEINTERNET__Si
0                          0.0                     1.0
1                          1.0                     0.0
2                          0.0                     1.0
3                          0.0                     1.0
4                          0.0                     1.0
...                        ...                     ...
692495                     0.0                     1.0
692496                     0.0                     1.0
692497                     0.0                     1.0
692498                     1.0                     0.0
692499                     0.0                     1.0

[692500 rows x 2 columns]

In [190]:
#concatenamos la columna de Fami tiene internet
y = pd.concat([FAMI_TIENEINTERNET_df, y], axis=1).drop('FAMI_TIENEINTERNET', axis=1)
y.shape

(692500, 8)

In [191]:
#Ahora, podemos concatenar la columna de las horas a la semana que trabaja cada estudiante
y = pd.concat([ESTU_HORASSEMANATRABAJA_df, y], axis=1).drop('ESTU_HORASSEMANATRABAJA', axis=1)
y.shape

(692500, 13)

In [192]:
#hacemos lo mismo para la columna de educacion padre
y = pd.concat([FAMI_EDUCACIONPADRE_df, y], axis=1).drop('FAMI_EDUCACIONPADRE', axis=1)
y.shape

(692500, 23)

se obtienen nuevas formas del dataframe

In [193]:
"""
Ahora, se tiene un nuevo dataframe, con las columnas de estrato de vivienda, las horas a la semana que trabaja cada estudiante, el valor de la matricula
de la universidad, si el estudiante paga matricula propia, la educación del padre y la columna de si la familia tiene internet  con sus respectivos valores númericos.Tambien se
cuentan con la columna de rendimiento global de los estudiantes. Además, se cambian la cantidad de columnas que tiene el dataframe
"""
y.head()

,FAMI_EDUCACIONPADRE__Educación profesional completa,FAMI_EDUCACIONPADRE__Educación profesional incompleta,FAMI_EDUCACIONPADRE__Ninguno,FAMI_EDUCACIONPADRE__Postgrado,FAMI_EDUCACIONPADRE__Primaria completa,FAMI_EDUCACIONPADRE__Primaria incompleta,FAMI_EDUCACIONPADRE__Secundaria (Bachillerato) completa,FAMI_EDUCACIONPADRE__Secundaria (Bachillerato) incompleta,FAMI_EDUCACIONPADRE__Técnica o tecnológica completa,FAMI_EDUCACIONPADRE__Técnica o tecnológica incompleta,...,ESTU_HORASSEMANATRABAJA__Entre 21 y 30 horas,ESTU_HORASSEMANATRABAJA__Menos de 10 horas,ESTU_HORASSEMANATRABAJA__Más de 30 horas,ESTU_HORASSEMANATRABAJA__no info,FAMI_TIENEINTERNET__No,FAMI_TIENEINTERNET__Si,FAMI_ESTRATOVIVIENDA,ESTU_PAGOMATRICULAPROPIO,ESTU_VALORMATRICULAUNIVERSIDAD,RENDIMIENTO_GLOBAL
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,3.0,0,0.625,medio-alto
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0,0.325,bajo
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,3.0,0,0.325,bajo
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.0,0,0.475,alto
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0,0.325,medio-bajo

In [194]:
#Luego, para poder llevar a este dataset a que todo en el sea numerico, podemos hacer el mismo procedimiento para la columna de rendimiento global
R_col = 'RENDIMIENTO_GLOBAL'

rmap = {'alto': 3, 'bajo':0, 'medio-bajo':1, 'medio-alto':2}
y[R_col] = [rmap[i] for i in y[R_col]]
y.head()

#Finalmente, estos datos nos muestran la columna de las horas a la semana que trabaja cada estudiante y la columna de de la educacion del padre  con el one-hot enconding y el resto de columnas ya estan en datos numericos.

,FAMI_EDUCACIONPADRE__Educación profesional completa,FAMI_EDUCACIONPADRE__Educación profesional incompleta,FAMI_EDUCACIONPADRE__Ninguno,FAMI_EDUCACIONPADRE__Postgrado,FAMI_EDUCACIONPADRE__Primaria completa,FAMI_EDUCACIONPADRE__Primaria incompleta,FAMI_EDUCACIONPADRE__Secundaria (Bachillerato) completa,FAMI_EDUCACIONPADRE__Secundaria (Bachillerato) incompleta,FAMI_EDUCACIONPADRE__Técnica o tecnológica completa,FAMI_EDUCACIONPADRE__Técnica o tecnológica incompleta,...,ESTU_HORASSEMANATRABAJA__Entre 21 y 30 horas,ESTU_HORASSEMANATRABAJA__Menos de 10 horas,ESTU_HORASSEMANATRABAJA__Más de 30 horas,ESTU_HORASSEMANATRABAJA__no info,FAMI_TIENEINTERNET__No,FAMI_TIENEINTERNET__Si,FAMI_ESTRATOVIVIENDA,ESTU_PAGOMATRICULAPROPIO,ESTU_VALORMATRICULAUNIVERSIDAD,RENDIMIENTO_GLOBAL
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,3.0,0,0.625,2
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0,0.325,0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,3.0,0,0.325,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.0,0,0.475,3
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0,0.325,1